# Generated by Django 5.1 on 2024-11-22 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedores',
            fields=[
                ('id_proveedor', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('nombre_p', models.CharField(max_length=100)),
                ('telefono_p', models.CharField(max_length=20)),
                ('email_p', models.EmailField(max_length=100)),
                ('direccion_p', models.CharField(max_length=200)),
                ('ciudad_p', models.CharField(max_length=100)),
                ('id_empleado', models.IntegerField()),
            ],
        ),
    ]
