# Generated by Django 5.1 on 2024-11-22 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id_pago', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('fecha_venta', models.DateField()),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo', models.CharField(max_length=50)),
                ('descripcion_compra', models.CharField(max_length=255)),
                ('id_producto', models.CharField(max_length=10)),
            ],
        ),
    ]
